version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS -p -e none https://521114670123.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t lamp:latest .
      - docker tag lamp:latest 521114670123.dkr.ecr.us-east-1.amazonaws.com/lamp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 521114670123.dkr.ecr.us-east-1.amazonaws.com/lamp:latest
